version: '3.8'
services:
  admin_backend:
    networks:
      - reward-network
    container_name: admin_backend
    ports:
      - "8003:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - admin_db

  admin_queue:
    container_name: admin_queue
    build: .
    command: 'php artisan queue:work'
    depends_on:
      - admin_db
    networks:
      - reward-network

  admin_db:
    container_name: admin_db
    networks:
      - reward-network
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql

networks:
  reward-network:
    external: true
