version: "3.9"
services:
  email_queue:
    container_name: email_queue
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - email_ms_db
    command: 'php artisan queue:work'

  email_ms_db:
    container_name: email_ms_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: emails
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33068:3306"

  email_mailhog:
    container_name: email_mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1026:1025" # smtp server
      - "8026:8025" # web ui
