version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: 'php artisan serve --host=0.0.0.0'

#  queue:
#    build: .
#    command: 'php artisan queue:work'
#    environment:
#      CACHE_DRIVER: file
#    depends_on:
#      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

  mailhog:
    container_name: ambassador_mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  redis:
    image: redis
    ports:
      - "6379:6379"
