version: '3.8'
services:
  users_backend:
    networks:
      - reward-network
    container_name: users_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - users_db
    ports:
      - "8002:8000"

  users_db:
    container_name: users_db
    networks:
      - reward-network
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33069:3306"

networks:
  reward-network:
    external: true