version: '3.8'
services:
  checkout_backend:
    networks:
      - reward-network
    container_name: checkout_backend
    ports:
      - "8004:8000"
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - checkout_db

  checkout_queue:
    container_name: checkout_queue
    build: .
    command: 'php artisan queue:work'
    depends_on:
      - checkout_db
    networks:
      - reward-network

  checkout_db:
    container_name: checkout_db
    networks:
      - reward-network
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql

networks:
  reward-network:
    external: true
